language: cpp

compiler:
    - gcc

addons:
  apt:
    packages:
      - cmake

os:
    - linux
    
sudo: true

dist: trusty

git:
  depth: false
  submodules: false

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55

script:
  - source /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qmake
  - make
    
branches:
  only:
    master

notifications:
    email:
      on_success: always
      on_failure: always
